name: koko

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: test secrets
        env:
          TOTO: ${{ secrets.PEM }}
        run: |
          echo hello
          echo $TOTO

