name: Auto Pull Changes (All Branches)

on:
  workflow_call:
    inputs:
      commands:
        description: 'Commands to run after pulling the latest code'
        required: true
        default: 'echo "No commands to run"'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: GraduationProjectSAMS/Workflows
          ref: main

      - name: Setup SSH for Access
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Run commands passed from the child workflow
            bash -c "${{
                inputs.commands
              }}"
          echo "Commands executed successfully"