name: Auto Pull Changes (All Branches)

on:
  workflow_call:
    inputs:
      commands:
        description: 'Commands to run after pulling the latest code'
        required: true
        default: 'echo "No commands to run"'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: GraduationProjectSAMS/Workflows
          ref: main

      - name: ls
        run: |
          echo "inventory : $(cat inventory.ini)"
          for host in $(grep -Eo '^[a-zA-Z0-9.-]+' inventory.ini); do
            echo "Adding $host to known_hosts"
            ssh-keyscan -H $host >> ~/.ssh/known_hosts 2>/dev/null || {
              echo "Warning: $host is unreachable or failed to add to known_hosts"
              echo "$host" >> unresolved_hosts.txt
            }
          done